### ISSUE TITLE
Invalid syntax of string declaration

### ISSUE THREAD

**Issue by mudrd8mz** [IT-Kartellet/moodle-auth_unilogin#1]
The string

```
$string['login_behaviour_description'] = "How should the page ... like so: {$CFG->wwwroot}/login/index.php?unilogin=false.";
```

The usage of $CFG in language string files is invalid. See the relevant section at https://docs.moodle.org/dev/Plugin_contribution_checklist

If the current site's URL is needed in the string, you should pass it via {$a} placeholder and populate the value in the code that calls `get_string()`.

**Comment by janmeier** [comment]
Roger, on it
